services:
    ollama:
        image: ollama/ollama
        container_name: ollama
        restart: unless-stopped
        ports:
            - "11434:11434"
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]
        entrypoint:
            [
                "/bin/bash",
                "-c",
                "ollama serve & sleep 5 && ollama pull deepseek-llm:7b && wait",
            ]
        volumes:
            - ollama-storage:/root/.ollama

    backend:
        build: ./backend
        container_name: faiss-backend
        ports:
            - "5000:5000"
        environment:
            - OLLAMA_API=http://ollama:11434/api/generate
        volumes:
            - ./backend/data.csv:/app/data.csv
        depends_on:
            - ollama

volumes:
    ollama-storage:
