name: Deploy to Raspberry Pi

# Trigger on pushes to main (or whichever branch)
on:
    push:
        branches:
            - main

jobs:
    deploy:
        # Use your self-hosted runner
        runs-on: self-hosted

        steps:
            # 1. Checkout the repo
            - name: Checkout code
              uses: actions/checkout@v3

            # 3. Build and start Docker Compose
            - name: Build and run Docker Compose
              env:
                  OLLAMA_MODEL: ${{ vars.OLLAMA_MODEL }}
                  CLOUDFLARE_TOKEN: ${{secrets.OLLAMA_MODEL}}
                  USE_GPU: ${{ vars.USE_GPU }}
              run: |
                  if [ "$USE_GPU" = "true" ]; then
                    docker compose -f docker-compose.gpu.yml up --build -d --force-recreate --remove-orphans
                  else
                    docker compose -f docker-compose.yml up --build -d --force-recreate --remove-orphans
                  fi
